/*
Autor: Salvador Elioenai Antonio Pérez. 
Fecha de Creacion: 05 de Junio del 2022.
Fecha de Actualizacion: 19 de Junio del 2022.
Descripción: JFrame Gato, este es el ultimo JFrame, aqui llega toda la 
información de los jugadores, aqui es donse se juego.
 */
package Modell;

import Pojo.JugadorX;
import static java.awt.Color.black;
import static java.awt.Color.gray;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Elioenaí
 */
public class Gato extends javax.swing.JFrame {

    private boolean estado = true; // si es true se puede escribir
    private String turno = "X";// Turno nos ayudara a establecer con que jugador
                               //empezara
    JLabel lbs[] = new JLabel[9];//Arreglo de Labels para posiciones
    int vs[][];

    /**
     * Recibimos los datos de los jugadores, su nombre y su iconos
     */
    public Gato(String jugadorx, String jugadoro, ImageIcon iconox, ImageIcon icono1) {
        this.vs = new int[][]{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {1, 4, 7}, {2, 5, 8}, {3, 6, 9}, {1, 5, 9}, {3, 5, 7}};
        initComponents();
        recibenombrex.setText(jugadorx);
        recibenombreo.setText(jugadoro);
        iconx.setIcon(iconox);
        iconxo.setIcon(icono1);
        setLocationRelativeTo(null);
        lbs[0] = jLabel1;
        lbs[1] = jLabel2;
        lbs[2] = jLabel3;
        lbs[3] = jLabel4;
        lbs[4] = jLabel5;
        lbs[5] = jLabel6;
        lbs[6] = jLabel7;
        lbs[7] = jLabel8;
        lbs[8] = jLabel9;

    }

    /*
        Constructor vacio
     */
    public Gato() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGato = new javax.swing.JPanel();
        LineasGato = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fontGato = new javax.swing.JLabel();
        NuevaPartida = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Reiniciar1 = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        Puntosx = new javax.swing.JLabel();
        Puntoso = new javax.swing.JLabel();
        recibenombrex = new javax.swing.JLabel();
        recibenombreo = new javax.swing.JLabel();
        iconx = new javax.swing.JLabel();
        iconxo = new javax.swing.JLabel();
        cajonx = new javax.swing.JLabel();
        Turno = new javax.swing.JLabel();
        cajonx1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        PanelGato.setBackground(new java.awt.Color(0, 0, 0));
        PanelGato.setForeground(new java.awt.Color(0, 0, 0));
        PanelGato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LineasGato.setBackground(new java.awt.Color(12, 19, 99));
        LineasGato.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        LineasGato.add(jLabel2);
        jLabel2.setBounds(106, 0, 100, 100);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        LineasGato.add(jLabel3);
        jLabel3.setBounds(212, 0, 100, 100);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        LineasGato.add(jLabel4);
        jLabel4.setBounds(0, 106, 100, 100);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        LineasGato.add(jLabel5);
        jLabel5.setBounds(106, 106, 100, 100);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        LineasGato.add(jLabel6);
        jLabel6.setBounds(212, 106, 100, 100);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        LineasGato.add(jLabel8);
        jLabel8.setBounds(106, 212, 100, 100);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        LineasGato.add(jLabel9);
        jLabel9.setBounds(212, 212, 100, 100);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        LineasGato.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 100);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        LineasGato.add(jLabel7);
        jLabel7.setBounds(0, 212, 100, 100);

        PanelGato.add(LineasGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 310, 310));

        fontGato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/a.png"))); // NOI18N
        PanelGato.add(fontGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 510, 450));

        NuevaPartida.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        NuevaPartida.setForeground(new java.awt.Color(255, 255, 255));
        NuevaPartida.setText("Nueva Partida");
        NuevaPartida.setBorder(null);
        NuevaPartida.setContentAreaFilled(false);
        NuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaPartidaActionPerformed(evt);
            }
        });
        PanelGato.add(NuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, -1));

        Salir.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setBorder(null);
        Salir.setContentAreaFilled(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        PanelGato.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, -1, -1));

        Reiniciar1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Reiniciar1.setForeground(new java.awt.Color(255, 255, 255));
        Reiniciar1.setText("Reiniciar Puntos");
        Reiniciar1.setBorder(null);
        Reiniciar1.setContentAreaFilled(false);
        Reiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reiniciar1ActionPerformed(evt);
            }
        });
        PanelGato.add(Reiniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, -1, -1));

        Reiniciar.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        Reiniciar.setText("Reiniciar Gato");
        Reiniciar.setBorder(null);
        Reiniciar.setContentAreaFilled(false);
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });
        PanelGato.add(Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, -1, -1));

        Puntosx.setBackground(new java.awt.Color(255, 255, 255));
        Puntosx.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Puntosx.setForeground(new java.awt.Color(255, 255, 255));
        Puntosx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntosx.setText("0");
        PanelGato.add(Puntosx, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 130, 30));

        Puntoso.setBackground(new java.awt.Color(255, 255, 255));
        Puntoso.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Puntoso.setForeground(new java.awt.Color(255, 255, 255));
        Puntoso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntoso.setText("0");
        PanelGato.add(Puntoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 120, 30));

        recibenombrex.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        recibenombrex.setForeground(new java.awt.Color(255, 255, 255));
        recibenombrex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelGato.add(recibenombrex, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 220, 30));

        recibenombreo.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        recibenombreo.setForeground(new java.awt.Color(255, 255, 255));
        recibenombreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelGato.add(recibenombreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 220, 30));
        PanelGato.add(iconx, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 180, 170));
        PanelGato.add(iconxo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 180, 170));

        cajonx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Anotación_2022-06-18_142624-removebg-preview (2).png"))); // NOI18N
        PanelGato.add(cajonx, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 600, 320));

        Turno.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        Turno.setForeground(new java.awt.Color(255, 255, 255));
        Turno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Turno.setText("Turno de X");
        PanelGato.add(Turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 360, 40));

        cajonx1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Anotación_2022-06-18_142624-removebg-preview (2).png"))); // NOI18N
        PanelGato.add(cajonx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 600, 320));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/logo.png"))); // NOI18N
        PanelGato.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 200, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/sci-fi-futuristic-user-interface-hud-template-frame-design-technology-abstract-background-vector.jpg"))); // NOI18N
        PanelGato.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1482, 816));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        presionar(2);
    }//GEN-LAST:event_jLabel2MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        presionar(3);
    }//GEN-LAST:event_jLabel3MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        presionar(4);
    }//GEN-LAST:event_jLabel4MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        presionar(5);
    }//GEN-LAST:event_jLabel5MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        presionar(6);
    }//GEN-LAST:event_jLabel6MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        presionar(8);
    }//GEN-LAST:event_jLabel8MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        presionar(9);
    }//GEN-LAST:event_jLabel9MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        presionar(1);
    }//GEN-LAST:event_jLabel1MousePressed
    /*
        Evento Mouse Pressed para los labels, asi podremos dejar una marca.
     */
    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        presionar(7);
    }//GEN-LAST:event_jLabel7MousePressed

    /*
        Este metodo nos ayudara a iniciar una nueva partida con los mismos
        jugadores.
     */
    private void NuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaPartidaActionPerformed
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");
            lbs[i].setBackground(black);
            estado = true;
        }

        if (turno.equals("X")) {
            turno = "O";
        } else {
            turno = "X";
        }

        Turno.setText("Turno de " + turno);

    }//GEN-LAST:event_NuevaPartidaActionPerformed

    /*
            Boton para salir del juego.
     */
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /*
        Método para reiniviar el juego, regustraremos nuevos jugadores.
     */
    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        JugadorX jugadorx = new JugadorX();
        jugadorx.setVisible(true);
        this.setVisible(false);
        this.hide();

    }//GEN-LAST:event_ReiniciarActionPerformed

    private void Reiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reiniciar1ActionPerformed
        Puntosx.setText("0");
        Puntoso.setText("0");
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");
            lbs[i].setBackground(black);
            estado = true;
        }

        if (turno.equals("X")) {
            turno = "O";
        } else {
            turno = "X";
        }

        Turno.setText("Turno de " + turno);


    }                                         

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Puntosx.setText("0");
        Puntoso.setText("0");
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");
            lbs[i].setBackground(black);
            estado = true;
        }

        if (turno.equals("X")) {
            turno = "O";
        } else {
            turno = "X";
        }

        Turno.setText("Turno de " + turno);

    }//GEN-LAST:event_Reiniciar1ActionPerformed
    /*
        Método que al presionar una casilla el jugador deje su marca.
     */
    public void presionar(int casilla) {
        if (lbs[casilla - 1].getText().equals("") && estado) {
            lbs[casilla - 1].setText(turno);
            cambiarturno();
            comprobarganador();
        }
    }

    /*
        Método para cambiar turno entre los dos jugadores.
     */
    public void cambiarturno() {
        if (turno.equals("X")) {
            turno = "O";
        } else {
            turno = "X";
        }
        Turno.setText("Turno de " + turno);
    }

    /**
     * Funcion para comprobar el ganador de la partida
     */
    public void comprobarganador() {
        for (int[] v : vs) {
            if (lbs[v[0] - 1].getText().equals("X") && lbs[v[1] - 1].getText().equals("X") && lbs[v[2] - 1].getText().equals("X")) {
                lbs[v[0] - 1].setBackground(gray);
                lbs[v[1] - 1].setBackground(gray);
                lbs[v[2] - 1].setBackground(gray);
                Puntosx.setText(Integer.toString(Integer.parseInt(Puntosx.getText()) + 1));
                //PuntosX.setText(Integer.toString(Integer.parseInt(PuntosX.getText()) + 1));
                estado = false;
                Turno.setText("Ganó Jugador X");
            }
            if (lbs[v[0] - 1].getText().equals("O") && lbs[v[1] - 1].getText().equals("O") && lbs[v[2] - 1].getText().equals("O")) {
                lbs[v[0] - 1].setBackground(gray);
                lbs[v[1] - 1].setBackground(gray);
                lbs[v[2] - 1].setBackground(gray);
                Puntoso.setText(Integer.toString(Integer.parseInt(Puntoso.getText()) + 1));
                Turno.setText("Ganó Jugador O");
                //PuntosO.setText(Integer.toString(Integer.parseInt(PuntosO.getText()) + 1));
                estado = false;
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel LineasGato;
    private javax.swing.JButton NuevaPartida;
    private javax.swing.JPanel PanelGato;
    private javax.swing.JLabel Puntoso;
    private javax.swing.JLabel Puntosx;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton Reiniciar1;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Turno;
    private javax.swing.JLabel cajonx;
    private javax.swing.JLabel cajonx1;
    private javax.swing.JLabel fontGato;
    private javax.swing.JLabel iconx;
    private javax.swing.JLabel iconxo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel recibenombreo;
    private javax.swing.JLabel recibenombrex;
    // End of variables declaration//GEN-END:variables
}
