/*
Autor: Salvador Elioenai Antonio Pérez. 
Fecha de Creacion: 05 de Junio del 2022.
Fecha de Actualizacion: 19 de Junio del 2022.
Descripción: JFrame JugadorO donde registraremos al jugador o,
recibimos el nombre del jugador x y su avatar, despues nos iremos a la clase
AvataresO.
 */
package Pojo;

import static Pojo.AvataresX.iconox;
import static Pojo.JugadorX.jugadorx;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class JugadorO extends javax.swing.JFrame {

    /*
        Esta variable nos ayudara a guardar el nombre del jugador o,
        sera de tipo publico ya que estaremos pasando la informacion por
        las clases.
     */
    public static String jugadoro = "";

    public JugadorO(String jugadorx, ImageIcon icono) {
        initComponents();
        setLocationRelativeTo(null);
    }

    /*
        Constructor vacio
     */
    public JugadorO() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Confirmar = new javax.swing.JButton();
        NombreO = new javax.swing.JTextField();
        AvisoO = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 180, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirmar.setBackground(new java.awt.Color(0, 0, 0));
        Confirmar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/confirmar (2).png"))); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.setBorder(null);
        Confirmar.setBorderPainted(false);
        Confirmar.setContentAreaFilled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 180, 40));

        NombreO.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        NombreO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreOActionPerformed(evt);
            }
        });
        jPanel1.add(NombreO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 250, 40));

        AvisoO.setBackground(new java.awt.Color(0, 0, 0));
        AvisoO.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        AvisoO.setForeground(new java.awt.Color(255, 255, 255));
        AvisoO.setText("Jugador O");
        AvisoO.setBorder(null);
        AvisoO.setBorderPainted(false);
        AvisoO.setContentAreaFilled(false);
        AvisoO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvisoOActionPerformed(evt);
            }
        });
        jPanel1.add(AvisoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 130, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/sci-fi-futuristic-user-interface-hud-template-frame-design-technology-abstract-background-vector_1.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
        Enviamos el nombre del jugador o, jugador x, el icono del jugador x
        al siguiente JFrame ( AvataresO )
     */
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        if (NombreO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Necesitas registrarte para Jugar", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            jugadoro = NombreO.getText();
            AvataresO saltar = new AvataresO(jugadorx, jugadoro, iconox);
            saltar.setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void NombreOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreOActionPerformed

    }//GEN-LAST:event_NombreOActionPerformed

    private void AvisoOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvisoOActionPerformed

    }//GEN-LAST:event_AvisoOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugadorO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugadorO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugadorO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugadorO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugadorO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvisoO;
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField NombreO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

}
